[package]
name = "yavhdl"
version = "0.0.1"
authors = ["Robert Ou <rqou@robertou.com>"]
build = "build.rs"

[profile.release]
lto = true

[lib]
name = "yavhdl"
crate-type = ["rlib", "staticlib"]

[build-dependencies]
bindgen = "0.23"
